### ISSUE TITLE
Inconsistenze a causa di un ritardato aggiornamento della Dashboard ISS

### ISSUE THREAD

**Issue by opencovid-mr** [floatingpurr/covid-19_sorveglianza_integrata_italia#1]
A causa di un ritardato aggiornamento della Dashboard ISS (l'aggiornamento del 15/12 è avvenuto dopo la mezzanotte e quindi in data 16/12) risultano al momento le seguenti inconsistenze:

- I dati della cartella [16-12-2020](https://github.com/floatingpurr/covid-19_sorveglianza_integrata_italia/tree/main/data/16-12-2020) sono relativi all'aggiornamento del 15/12.

- I dati della cartella [17-12-2020](https://github.com/floatingpurr/covid-19_sorveglianza_integrata_italia/tree/main/data/17-12-2020) sono relativi all'aggiornamento del 15/12.

Per evitare ripercussioni "a catena" l'inconsistenza andrebbe sanata quanto prima correggendo i nomi della cartelle sopra indicate.

Per evitare che questo "inconveniente" possa ripetersi in futuro, si potrebbe modificare il file[get_data.yml](https://github.com/floatingpurr/covid-19_sorveglianza_integrata_italia/blob/main/.github/workflows/get_data.yml) in modo che il controllo sulla data venga effettuato in base alla data indicata nella colonna **iss_date** presente in ogni file CSV estratto.

**Comment by floatingpurr** [comment]
Ciao, sto per commitare un fix dei dati. Sicuramente la procedura va migliorata ed integrata di conseguenza nel workflow automatico. Devo trovare il tempo per farlo. Se nel frattempo qualcuno vuole contribuire al codice con una PR, ancora meglio.

**Comment by floatingpurr** [comment]
PS: Il #2 sembra un problema di natura diversa, forse legato direttamente a come sono stati rilasciati i dati.
