### ISSUE TITLE
Dati del 18/01/2021 e 20/01/2021

### ISSUE THREAD

**Issue by Scuolanocovid** [floatingpurr/covid-19_sorveglianza_integrata_italia#3]
Non sono stati recuperati in modo automatico, verificare il perché. 
Eventualmente comunicarne anche il motivo.
Grazie.

**Comment by floatingpurr** [comment]
tl;dr: Il problema è relativo al file di origine che talvolta contiene date inconsistenti. Non ho nessun contatto con l'emittente del dato e non ho modo di segnalare e correggere eventuali errori. 

Lo storico loggato in questo repo è alimentato da una procedura automatica. Non c'è modo di calcolare un consenso sulla data, per cui i file risentono di queste problematiche. Allego a titolo esemplificativo il file odierno dove i dati delle province seguono una data diversa dalle altre [covid_19-iss.xlsx](https://github.com/floatingpurr/covid-19_sorveglianza_integrata_italia/files/5872610/covid_19-iss.xlsx).

Chiudo questa issue ASAP col commit di notifica del problema nel readme. Grazie
