### ISSUE TITLE
Inconsistenza dati su casi e decessi

### ISSUE THREAD

**Issue by antoniocaramia** [floatingpurr/covid-19_sorveglianza_integrata_italia#4]
Vi sono alcune inconsistenze nei dati relativi a casi e decessi.
In particolare per alcuni giorni i casi ottenuti come somma di M + F sono inferiori a quelli del giorno precedente.
Di seguito le anomalie:

**++CASI++**
**22/12/2020**: somma del campo "c_90+" = 55476 mentre il 21/12/2020 era 55648; 

**04/02/2021**: TUTTI i campi riportano un valore inferiore a quello presente al 03/02/2021
  

**++DECESSI++**
**14/12/2020**: i decessi del campo "d_20_29" sono 2 in meno rispetto al 13/12/2020

**22/12/2020**: i decessi del campo "d_20_29" sono 1 in meno rispetto al 21/12/2020

**23/12/2020**: i decessi del campo "d_30_39" sono 1 in meno rispetto al 22/12/2020

**24/12/2020**: i decessi del campo "d_30_39" sono 1 in meno rispetto al 23/12/2020

**Dal 5 al 10 gennaio 2021** i decessi nella **fascia 0-9** risultano essere **10** (dato cumulato).
L'**11 gennaio** i decessi **0-9** diventano **7**
Il **13 gennaio** tornano a **4**
Il **22 gennaio** diventano **7**.

Vi sono inoltre altre anomalie in altre fasce di età che sono evidenziate in giallo nell'immagine sotto riportata:

![immagine](https://user-images.githubusercontent.com/63555593/117947352-65945280-b310-11eb-90cb-edef66ef8868.png)

**Comment by floatingpurr** [comment]
Ciao @antoniocaramia, ti ringrazio per questa segnalazione. In questo repository mi occupo solo di copiare i file esposti dall'Istituto Superiore di Sanità. E' probabile che ci sia stato un problema sul conteggio all'origine. Purtroppo però non è un dato che posso controllare.
