### ISSUE TITLE
Dati stato clinico dal 2/6

### ISSUE THREAD

**Issue by Paulsword** [floatingpurr/covid-19_sorveglianza_integrata_italia#5]
Buongiorno,

dal 2/6 i dati relativi allo stato clinico dei pazienti hanno subito una modificazione improvvisa, che pare frutto di una diversa classificazione, dal momento che in ogni fascia di età le percentuali dei casi critici sono aumentate significativamente (complessivamente dallo 0,69% al 2%). Trattandosi di dati riferiti agli attualmente positivi, non è pensabile che si tratti di modificazione reale, ma di cambio metodologico, meno probabilmente di errore (che si ripete nei giorni successivi).
Vi risulta che sia stata data notizia al riguardo?

Grazie mille

**Comment by floatingpurr** [comment]
Ciao @Paulsword. Purtroppo non so darti una risposta. In questo repo, faccio uno scraping abbastanza naive del file, senza entrarne nel merito. Cerco di mantenere una sorta di storico.
