### ISSUE TITLE
CSV 2021-06-08 "vuoti" (solo cella A1)

### ISSUE THREAD

**Issue by opencovid-mr** [floatingpurr/covid-19_sorveglianza_integrata_italia#6]
I CSV della [cartella](https://github.com/floatingpurr/covid-19_sorveglianza_integrata_italia/tree/main/data/2021-06-08) relativa al giorno 2021-06-08 contengono il contenuto della sola cella A1.

Una modifica al file parser.py (modifica 'tampone' e quindi molto grezza) per recuperare i dati si trova [qui](
https://github.com/opencovid-mr/covid-19_sorveglianza_integrata_italia/blob/main/parser.py).

**Comment by floatingpurr** [comment]
Chiudo PR #7

**Comment by floatingpurr** [comment]
Ciao @opencovid-mr grazie per la segnalazione. Credo che ci sia stato un problema transitorio sul file di origne.

**Comment by floatingpurr** [comment]
Soluzione tampone trovata.

Vediamo il prossimo giro.

**Comment by floatingpurr** [comment]
Lascio per referenza il file che ha originato il problema [bad_data.xlsx](https://github.com/floatingpurr/covid-19_sorveglianza_integrata_italia/files/6625176/bad_data.xlsx)

**Comment by floatingpurr** [comment]
Sembra tornato tutto ok dal ea5e8fb. Per ora chiudo. Grazie per l'aiuto!

**Comment by Paulsword** [comment]
Scusate, ma il problema persiste. Se cerco di importare da https://raw.githubusercontent.com/floatingpurr/covid-19_sorveglianza_integrata_italia/main/data/latest/stato_clinico.csv, Excel trova sempre solo una singola cella.
Mi aiutate?

**Comment by floatingpurr** [comment]
Ciao @Paulsword, purtroppo c'era un problema di compatibilità tra il nuovo formato del file ed il modo con cui recuperavo i dati. Ora dovrei aver fatto un fix definitivo. Fammi sapere se trovi ancora qualcosa di strano sul tema.

**Comment by Paulsword** [comment]
@floatingpurr grazie. Purtroppo non riesco ancora ad importare il contenuto. Excel trova solo la prima cella.

**Comment by floatingpurr** [comment]
Ciao, non ho capito bene il problema. I dati ora ci sono. Mi descriveresti meglio cosa vorresti ottenere ed i passaggi che fai?

**Comment by Paulsword** [comment]
Sì infatti i dati li vedo, ma se provo ad importarli da Excel, non funziona, così come non funziona (più) l'import dal file originario dell'ISS.
In particolare, da Excel > Dati > Da Web > URL > inserisco: https://raw.githubusercontent.com/floatingpurr/covid-19_sorveglianza_integrata_italia/main/data/latest/stato_clinico.csv
Vede solo Column 1: iss_date

**Comment by floatingpurr** [comment]
Ok, capito. Il repo ora è a posto. Si tratta di due problemi diversi. 

* Il file originale ha dei problemi di "formato", motivo per cui dà spesso problemi. Qui altre info: https://twitter.com/i_m_andrea/status/1403853018429337602?s=20

* se apri quell'url i dati ci sono. Credo che in questo caso sia soltanto un problema di caching di Excel. Prova a svuotare la cache, a aggiornare i dati o a usare questo url fittizio per invalidare la cache: https://raw.githubusercontent.com/floatingpurr/covid-19_sorveglianza_integrata_italia/main/data/latest/stato_clinico.csv?q=foo

**Comment by Paulsword** [comment]
Macché, non riesco. Mi dà sempre "DataFormat.Error: La tabella esterna non è nel formato previsto."
(Tieni conto che sono un medico.. abbi pazienza)

**Comment by Paulsword** [comment]
Correggo: riesco con un nuovo foglio Excel. Quindi dev'essere come dici tu un problema di cache.
Grazie molte

**Comment by floatingpurr** [comment]
Ma figurati, se posso aiutarti lo faccio volentieri!

~~Fammi capire un po' meglio la situazione:~~

* ~~prima importavi i dati in quel modo? Per esempio, [questa](https://raw.githubusercontent.com/floatingpurr/covid-19_sorveglianza_integrata_italia/main/data/2021-06-05/stato_clinico.csv) vecchia versione del dato la importi senza problemi?~~
* ~~io non uso molto Excel e non ho quel menu, se scarichi il file in locale e lo importi con CSV funziona?~~

EDIT: vista ora la risposta

**Comment by floatingpurr** [comment]
Riformulo perché abbiamo postato in contemporanea. Se è un problema di cache bisogna invalidarla e fargli scaricare di nuovo i dati. Puoi provare come ti consigliavo con l'url fittizia passando dei parametri. Oppure puoi usare questa url, che punta al medesimo file, puntando al path giornaliero: https://raw.githubusercontent.com/floatingpurr/covid-19_sorveglianza_integrata_italia/main/data/2021-06-12/stato_clinico.csv

**Comment by Paulsword** [comment]
Grazie molte. Avevo provato con l'url fittizia ma non riuscivo. Poi ho aperto una cartella nuova di Excel, provato il collegamento, e al messaggio di errore ho potuto chiedere di trasformare l'import, suggerire il separatore (",") e così è andato bene.
Fatto quello, me l'ha fatto fare anche nella cartella precedente, quindi evidentemente non era un problema della repo ma delle impostazioni locali su Excel.
Io in precedenza importavo direttamente dal file di ISS, che però dall'8/6 non risulta importabile (l'errore è : Dettagli: "Non è stato possibile riconoscere l'input come documento di Excel valido."). Qui probabilmente c'entra quello che riportavi tu su Twitter.
Ad ogni modo adesso riesco a prendere i dati bene dalla tua repo, e per questo ti ringrazio.

**Comment by floatingpurr** [comment]
Bene,prego! Contento che abbia trovato il modo per recuperare i dati. Buon lavoro!
