### ISSUE TITLE
Actions falliscono da qualche giorno

### ISSUE THREAD

**Issue by vi-enne** [floatingpurr/covid-19_sorveglianza_integrata_italia#8]
Come da titolo, non ho indagato nel codice per capire cosa stia succedendo.
Segnalo a @floatingpurr

**Comment by floatingpurr** [comment]
Grazie per la segnalazione. Controllo al più presto!

**Comment by floatingpurr** [comment]
Ciao @vi-enne. Era cambiato l'ordine delle colonne di un foglio del file Excel. Ho fatto un fix veloce, dovrebbe andare. Fammi sapere se dovessi vedere altre stranezze

**Comment by vi-enne** [comment]
Grazie, fatto fix anche nel mio codice.
